# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Compute package version
      id: version
      run: |
        VERSION="$(date +'%Y.%m').${{ github.run_number }}-beta"
        echo "Building version $VERSION"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 8.0.x

    - name: Setup Github Packages
      run: dotnet nuget add source --username ant-car --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/AV-Coders/index.json"

    - name: Restore dependencies
      id: restore
      run: dotnet restore

    - name: Build
      id: build
      run: dotnet build --no-restore

    - name: Test
      id: test
      run: dotnet test --no-build --verbosity normal

    - name: Pack NuGet packages
      id: pack
      run: dotnet pack "Crestron Components.sln" --output ./package /p:Version=${{ steps.version.outputs.version }} --configuration Release

    - name: Publish to GitHub Packages
      id: publish
      run: dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate

    - name: Notify on Error
      uses: skitionek/notify-microsoft-teams@master
      if: failure()
      with:
        webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}
